### ISSUE TITLE
Custom UUID field doesn't show

### ISSUE THREAD

**Issue by rbsam176** [bn-digital/strapi#6]
I have added the plugin to my Strapi app using `yarn add @bn-digital/strapi-plugin-field-uuid`, it is listed in the admin panel under General > Plugins > Field UUID, but going into Content-Type Builder > Add Another Field > Custom doesn't list UUID. Should I be manually including the plugin in some json file, I had assumed the plugin would take care of this, what am I missing?

**Comment by vladyslavvolkov** [comment]
No, just rebuild strapi after installing, that should be enough. Let me know if that works for you

**Comment by rbsam176** [comment]
That's worked, thanks @VladyslavVolkov - I didn't realise I had to rebuild for it to show 👍
